#!/usr/bin/env python3
"""
save_picks.py — Reads picks_output.json (generated by generate_picks.js) and
                merges new entries into picks_history.json.

generate_picks.js runs the ACTUAL getBettingPicks() from season-finish.html, so
picks here are identical to what the browser cards show — no Python reimplementation.

Workflow order (update-dashboard.yml):
  1. update_dashboard.py   → season-finish.html (fixture data)
  2. node generate_picks.js → picks_output.json  (canonical picks via real JS)
  3. python save_picks.py  → picks_history.json  (persist + top-pick marking)
"""

import json
import datetime
from pathlib import Path

BASE           = Path(__file__).parent
HISTORY_FILE   = BASE / "picks_history.json"
PICKS_OUTPUT   = BASE / "picks_output.json"   # written by generate_picks.js


def main():
    today_iso = datetime.date.today().isoformat()
    print(f"📝  Save picks — {today_iso}")

    if not PICKS_OUTPUT.exists():
        print(f"  ❌  picks_output.json not found — run 'node generate_picks.js' first")
        return

    with open(PICKS_OUTPUT, encoding="utf-8") as f:
        generated = json.load(f)
    print(f"  📦 {len(generated)} fixtures from picks_output.json")

    # Load existing history
    history = []
    if HISTORY_FILE.exists():
        with open(HISTORY_FILE, encoding="utf-8") as f:
            history = json.load(f)
    saved_ids = {e["id"] for e in history}

    added = 0
    for fx in generated:
        date_iso = fx.get("dateIso", "")
        league   = fx.get("league", "UNK")
        home     = fx.get("home", "?")
        away     = fx.get("away", "?")
        picks    = fx.get("picks", [])

        if not picks:
            continue

        mid = f"{date_iso}-{league}-{home}-{away}".replace(" ", "_").replace("/", "-")
        if mid in saved_ids:
            continue

        # Enrich picks: add result=None
        pick_entries = []
        for p in picks:
            pick_entries.append({
                "market":    p.get("market",    ""),
                "marketKey": p.get("marketKey", ""),
                "icon":      p.get("icon",      ""),
                "conf":      p.get("conf",      "medium"),
                "sc":        p.get("sc",        0),
                "odds":      p.get("odds"),
                "result":    None,
                "isTopCard": False,
            })

        entry = {
            "id":          mid,
            "date":        fx.get("date", ""),
            "dateIso":     date_iso,
            "league":      league,
            "leagueName":  fx.get("leagueName", ""),
            "leagueFlag":  fx.get("leagueFlag", ""),
            "home":        home,
            "away":        away,
            "eventId":     fx.get("eventId"),
            "matchScore":  fx.get("matchScore"),
            "picks":       pick_entries,
            "finalScore":  None,
            "resolved":    False,
            "savedAt":     datetime.datetime.utcnow().isoformat() + "Z",
        }
        history.append(entry)
        saved_ids.add(mid)
        added += 1
        pick_labels = ", ".join(p["market"] for p in pick_entries)
        flag = fx.get("leagueFlag", "")
        print(f"  + {flag} {home} vs {away} ({fx.get('date','')}) → {pick_labels}")

    # ── Re-apply fresh picks to unresolved entries within 2 days ─────────────
    # When picks change (e.g. new prematch data) for a not-yet-played match,
    # update the stored entry so it matches what the card currently shows.
    today_dt = datetime.date.fromisoformat(today_iso)
    # Build lookup from picks_output.json by (home, away, league)
    fresh_by_id: dict[str, dict] = {}
    for fx in generated:
        date_iso = fx.get("dateIso", "")
        mid = f"{date_iso}-{fx.get('league','')}-{fx.get('home','')}-{fx.get('away','')}".replace(" ","_").replace("/","-")
        fresh_by_id[mid] = fx

    refreshed = 0
    for e in history:
        if e.get("resolved"):
            continue
        try:
            e_date = datetime.date.fromisoformat(e["dateIso"])
        except Exception:
            continue
        # Only refresh entries within the last 2 days (unresolved recent + future)
        if e_date < today_dt - datetime.timedelta(days=2):
            continue

        fresh = fresh_by_id.get(e["id"])
        if not fresh or not fresh.get("picks"):
            continue

        # Check if picks changed meaningfully (different market key or odds)
        old_keys = [p.get("marketKey","") for p in e["picks"]]
        new_keys = [p.get("marketKey","") for p in fresh["picks"]]
        old_odds = [p.get("odds") for p in e["picks"]]
        new_odds = [p.get("odds") for p in fresh["picks"]]

        if old_keys == new_keys and old_odds == new_odds:
            continue  # Nothing changed

        # Preserve existing isTopCard flags by position
        new_picks = []
        for i, p in enumerate(fresh["picks"]):
            np = {
                "market":    p.get("market",    ""),
                "marketKey": p.get("marketKey", ""),
                "icon":      p.get("icon",      ""),
                "conf":      p.get("conf",      "medium"),
                "sc":        p.get("sc",        0),
                "odds":      p.get("odds"),
                "result":    None,
                "isTopCard": e["picks"][i].get("isTopCard", False) if i < len(e["picks"]) else False,
            }
            new_picks.append(np)
        e["picks"] = new_picks
        refreshed += 1
        flag = e.get("leagueFlag", "")
        new_labels = ", ".join(p["market"] for p in new_picks)
        print(f"  🔄 {flag} {e['home']} vs {e['away']} ({e['dateIso']}) → {new_labels}")

    if refreshed:
        print(f"\n♻️   {refreshed} Einträge mit frischen Picks aktualisiert")

    # ── Mark top picks (isTopCard) for today's entries ────────────────────────
    # Mirrors JS buildTopCardsHtml(): sc*10 + conf bonus + matchScore bonus.
    # Top 7 picks (rank ≥ 12, max 2 per match) get isTopCard=True.
    today_entries = [e for e in history if e.get("dateIso") == today_iso]
    if today_entries:
        for e in today_entries:
            for p in e["picks"]:
                p["isTopCard"] = False

        candidates = []
        for e in today_entries:
            ms = e.get("matchScore") or 0
            if ms < 10:
                continue  # Top Cards only from high-quality matches (matchScore ≥ 10)
            for idx, p in enumerate(e["picks"]):
                sc   = p.get("sc") or 0
                conf = p.get("conf", "low")
                rank = sc * 10
                rank += 4 if conf == "high" else 1 if conf == "medium" else 0
                rank += (ms - 6) * 2
                candidates.append((rank, e["id"], idx))

        candidates.sort(key=lambda x: -x[0])
        match_counts: dict[str, int] = {}
        top_count = 0
        for rank, eid, pidx in candidates:
            if rank < 12 or top_count >= 7:
                break
            if match_counts.get(eid, 0) >= 2:
                continue
            for e in today_entries:
                if e["id"] == eid:
                    e["picks"][pidx]["isTopCard"] = True
                    match_counts[eid] = match_counts.get(eid, 0) + 1
                    top_count += 1
                    break

        top_labels = [
            f"{e.get('leagueFlag','')} {e['home']} vs {e['away']} → {p['market']}"
            for e in today_entries for p in e["picks"] if p.get("isTopCard")
        ]
        print(f"\n🃏  Top Picks ({top_count}):")
        for lbl in top_labels:
            print(f"   ⭐ {lbl}")

    with open(HISTORY_FILE, "w", encoding="utf-8") as f:
        json.dump(history, f, ensure_ascii=False, indent=2)

    print(f"\n✅  {added} neue Einträge gespeichert  (total: {len(history)})")
    print(f"   Datei: {HISTORY_FILE}")


if __name__ == "__main__":
    main()
